backend:
  name: github
  repo: billymosis/my-blog

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: featuredImage, label: FeaturedImage, widget: image }
      - { name: body, label: Body, widget: markdown }

